version: '3'
services: 
  dev:
    container_name: water-jug-riddle
    stdin_open: true
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
    - 3000:3000
    tty: true
    command: ''
    volumes: 
    - ./:/app/node_modules
    - ./:/app

